config/routes.rb
Rails.application.routes.draw do
  resources :products

  devise_for :users
  root 'pages#home'

  get 'dashboard' => "pages#dashboard"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       can :read, :all
       can :manage, Product do |product|
        product.try(:user) == user
       end
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
  	redirect_to root_path, notice: "You are not authorized for this action"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action :authenticate_user!, only: [:dashboard]

  def home
  	if current_user
  		redirect_to products_path
  	end
  end

  def dashboard
  	@products = Product.where(:user => current_user)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:new,  :edit, :create, :update, :destroy]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    authorize! :manage, @product
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    authorize! :manage, @product
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    authorize! :manage, @product
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :descr1, :descr2, :price, :availability)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "marketplace", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <%= render "layouts/loggedin_user_navbar_right" %>
        <% else %>
          <%= render "layouts/loggedout_user_navbar_right" %> 
        <% end %> 
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_loggedin_user_navbar_right.html.erb
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello, <%= current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><%= link_to "Your Dashboard", dashboard_path%></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path%></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete%></li>
          </ul>
        </li>

app/views/layouts/_loggedout_user_navbar_right.html.erb
        <li><%= link_to "Login", new_user_session_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New here? Sign up", new_user_registration_path%></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
              <li><%= link_to "Login", new_user_session_path %></li>
          </ul>
        </li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Marketplace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>
<div class = "container">
  <% flash.each do |type, message|%>
    <div class = "alert alert-info fade-in">
    	<button class = "close" data-dismiss = "alert" >x</button>
    	<%= message %>
    </div>
  <%end%>
  <%= yield %>
</div>

</body>
</html>

app/views/pages/dashboard.html.erb
<div class = "row">
	<h1 class = "text-center">Dashboard</h1>

	<div class = "col-md-4">
		<h3 class = "text-center">Products <%= link_to "New Product", new_product_path, class: "btn btn-primary btn-sm"%>
		</h3>

		<table class="table table-condensed">
			<thead>
				<tr>
					<th>Id</th>
					<th>Name</th>
					<th>Price</th>
					<th>Action</th>
				</tr>
			</thead>

			<tbody>
				<% @products.each do |product| %>
				  <tr>
					  <td><%= product.id%></td>
					  <td><%= link_to product.name, product_path(product)%></td>
					  <td>$<%=product.price.to_f/100%></td>
					  <td><%= link_to "Edit", edit_product_path(product)%></td>
				  </tr>
				 <%end%>
			</tbody>
  
        </table>
	</div>

	<div class = "col-md-4">
		<h3 class = "text-center">My Purchases</h3>
	</div>

    <div class = "col-md-4">
    	<h3 class = "text-center">Sales</h3>
	</div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1>Welcome to marketplace</h1>
  <p>Find cool stuff here</p>
  <%= link_to "Products", products_path, class: "btn btn-primary btn-lg" %>
  <% if !current_user %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  <%end%>
</div>

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>


    <%= f.input :name, required: true, label: false, placeholder: "Name" %>
    <%= f.input :descr1, required: true,label: false,label: false,label: false, placeholder: "Description 1" %>
    <%= f.input :descr2, required: true,label: false,label: false, placeholder: "Description 2", input_html: {rows: 5}%>
    <%= f.input :price, required: true,label: false, placeholder: "Price" %>
    <%= f.input :availability, required: true %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/_product.html.erb
  <div class = "col-md-3">
    <div class = "thumbnail">
      <%= link_to product_path(product) do %>
        <%= image_tag "Product.jpg", class: "img-responsive" %>
      <%end%>
      <div class = "caption">
        <p><%=link_to product.name, product_path(product)%></p>
        <p>$<%=product.price.to_f/100%></p>
      </div>
    </div>
  </div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class = "row">
 <%= render @products %>
</div>

app/views/products/new.html.erb
<div class = "col-sm-6">
  <h1>New Product</h1>

  <%= render 'form' %>

  <%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<div class = "row">
  <div class = "col-md-6">
    <%= image_tag "Product.jpg", class: "img-responsive" %>
  </div>

  <div class = "col-md-6">
    <h2><%= @product.name%></h3>
    <h4>by <%= @product.descr1%></h2>
    <p><%= @product.descr2%></p>
    <h4>$<%= @product.price.to_f/100%></h4>
  </div>

</div>

</br>